[package]
name = "rustcat"
version = "1.0.0"
authors = ["robiot"]
description = "rustcat - Like Netcat but in Rust"
license = "MIT"
repository = "https://github.com/robiot/rustcat"
edition = "2018"

[[bin]]
name = "rc"
path = "src/main.rs"

[dependencies]
termion = "1.5.6"
getopts = "0.2"
rustyline = "8.2.0"
socket2 = "0.3.8"