[package]
name = "rustcat"
version = "0.0.4"
authors = ["robiot"]
description = "rustcat - Like Netcat but in Rust"
license = "MIT"
repository = "https://github.com/robiot/rustcat"
edition = "2018"

[dependencies]
termion = "1.5.6"
getopts = "0.2"
rustyline = "8.2.0"